sudo: false
language: c

compiler:
  - clang
  - gcc

#build: $(CC) --version && make test

before_script:
  - ${CC} --version

script: 
  # run test from Makefile
  - make test

after_success: true

after_failure: echo "Test failed!"

